name: final_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  shared_preferences: ^2.2.0
  google_fonts: ^4.0.1
  email_validator: ^2.1.17
  cupertino_icons: ^1.0.2
  ternav_icons: ^1.0.0
  camera: ^0.10.5+9
  socket_io_client: ^2.0.3+1
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  assets_audio_player: ^3.1.1
  flutter_colorpicker: ^1.0.3
  confetti: ^0.7.0
  provider: ^6.0.3
  audioplayers: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_spinkit: ^5.2.0

  carousel_slider: ^4.0.0
  persistent_bottom_nav_bar: ^5.0.2

  face_camera: ^0.0.9
  flare_flutter: ^3.0.2

  flutter_material_pickers: ^3.1.0
  path_provider: ^2.1.2

  intl: ^0.17.0
  flutter_tts: ^3.2.2
  flutter_local_notifications: ^8.0.0
  flutter_native_timezone: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  hive_generator: ^1.1.0
  build_runner: ^2.0.4




flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/calm/
    - assets/music/excite/
    - assets/music/happy/
    - assets/audio/



